src/RazorRen.Sample.Transformer/Pages/Admin/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorRen.Sample.Transformer.Pages.Admin
{
    public class IndexModel : PageModel
    {
        private readonly IHostingEnvironment env;
        private readonly RazorRen.Generator.Options razorRenOptions;

        public IndexModel(
            IHostingEnvironment env,
            RazorRen.Generator.Options razorRenOptions
        )
        {
            this.env = env;
            this.razorRenOptions = razorRenOptions;
        }

        public void OnGet()
        {

        }

        public IActionResult OnGetCleanup()
        {
            this.ClearFolder(Path.Combine(env.ContentRootPath, razorRenOptions.OutputPath));
            return Page();
        }

        public async Task<IActionResult> OnGetRenderAsync()
        {
            var baseuri =$"{Request.Scheme}://{Request.Host}/";
            var uris = new string[] {"", "About", "Contact" };

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseuri);
                HttpResponseMessage response;

                foreach (var uri in uris)
                {
                    response = await client.GetAsync(uri);
                }
            }
            return Page();
        }

        public IActionResult OnGetPublish()
        {
            if (!Directory.Exists(Path.Combine(env.ContentRootPath, "publish")))
            {
                Directory.CreateDirectory(Path.Combine(env.ContentRootPath, "publish"));
            }

            this.ClearFolder(Path.Combine(env.ContentRootPath, "publish"));

            CopyDirectory(new DirectoryInfo(Path.Combine(env.ContentRootPath, "wwwroot")),new DirectoryInfo(Path.Combine(env.ContentRootPath, "publish")));
            CopyDirectory(new DirectoryInfo(Path.Combine(env.ContentRootPath, razorRenOptions.OutputPath)),new DirectoryInfo(Path.Combine(env.ContentRootPath, "publish")));
            return Page();
        }

        private void ClearFolder(string folderPath)
        {
            DirectoryInfo dir = new DirectoryInfo(folderPath);

            foreach (FileInfo fi in dir.GetFiles())
            {
                fi.IsReadOnly = false;
                fi.Delete();
            }

            foreach (DirectoryInfo di in dir.GetDirectories())
            {
                ClearFolder(di.FullName);
                di.Delete();
            }
        }

        public static void CopyDirectory(DirectoryInfo source, DirectoryInfo target)
        {
            foreach (DirectoryInfo dir in source.GetDirectories())
                CopyDirectory(dir, target.CreateSubdirectory(dir.Name));

            foreach (FileInfo file in source.GetFiles())
                file.CopyTo(Path.Combine(target.FullName, file.Name));

        }  
    }
}

src/RazorRen.Sample.Transformer/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorRen.Sample.Transformer.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/RazorRen.Sample.Transformer/Pages/About.cshtml
@page

@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>

<p>Use this area to provide additional information.</p>

src/RazorRen.Sample.Transformer/Pages/Admin/Index.cshtml
@page
@model Admin.IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h2>@ViewData["Title"]</h2>

<p>Secret Admin Page!</p>

<a asp-page-handler="cleanup">Cleanup</a>

<a asp-page-handler="render">Render</a>

<a asp-page-handler="publish">Publish</a>

src/RazorRen.Sample.Transformer/Pages/Contact.cshtml
@page

@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/RazorRen.Sample.Transformer/Pages/Index.cshtml
@page

@{
    ViewData["Title"] = "Home page";
}

<h2>@ViewData["Title"]</h2>

<p>Awesome Sample Page!</p>

src/RazorRen.Sample.Transformer/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RazorRen.Sample.Transformer</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <ul class="nav navbar-nav">
        <li><a asp-page="/Index">Home</a></li>
        <li><a asp-page="/About">About</a></li>
        <li><a asp-page="/Contact">Contact</a></li>
        <li><a asp-page="/Admin/Index">Admin</a></li>
    </ul>
    @RenderBody()

    @RenderSection("Scripts", required: false)
</body>
</html>